### ISSUE TITLE
Support Racket on Chez Scheme

### ISSUE THREAD

**Issue by LiberalArtist** [tonyg/racket-unix-signals#1]
Because this package uses an extension module implemented in C, it doesn't work with Racket on Chez Scheme, which is now out of beta (though not yet the default distribution).

The ideal fix would be to rewrite `unix-signals-extension.c` in Racket and just use the FFI. It would also work to still have a small shared library written in C, just without `#include "escheme.h"` (which isn't supported for Racket-on-Chez).

I'm willing to try to contribute a patch, but I've never actually handled signals before, so it might take me a while.

**Comment by zentrope** [comment]
For what it's worth, I tried this (by downloading @LiberalArtist 's branch and running `make`) and it worked: on MacOS with Racket 7.8 on Chez.
